### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by hamtaro217** [sparkfun/Stranger_Things_Wall#3]
When loading the stranger_things.ino file in the Arduino IDE I get the following errors:

stranger_things.ino:11:14: error: variable or field ‘lightUp’ declared void
stranger_things.ino:11:14: error: ‘CHAR_LEDS’ was not declared in this scope
stranger_things.ino: In function ‘void loop()’:
stranger_things.ino:33:19: error: ‘lightUp’ was not declared in this scope

Any help is appreciated.

**Comment by mhord** [comment]
What version of the IDE are you using, and what target are you using?

This looks like a typo somewhere in the code...did you change anything?

**Comment by hamtaro217** [comment]
Thanks, it was the version I was using.  I updated to the latest version and it is working fine.
